apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: crudapp
  labels:
    name: crudapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: crudapp
  template:
    metadata:
      labels:
        name: crudapp
    spec:
      containers:
        - name: crudapp
          image: dilipkumarashok/crud-app:v1
          ports:
            - containerPort: 5005
          env:
            - name: MYSQL_DATABASE_HOST
              value: dbsql
